# Generated by Django 6.0.4 on 2026-04-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('enonce', models.TextField()),
                ('difficulte', models.IntegerField(default=1)),
                ('score_minimum', models.FloatField(default=0.5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='courses.module')),
            ],
        ),
    ]
