# Generated by Django 6.0.4 on 2026-04-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('exercises', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='module',
        ),
        migrations.AddField(
            model_name='exercice',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='courses.cours'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='reponse_correcte',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercice',
            name='type',
            field=models.CharField(choices=[('qcm', 'QCM'), ('code', 'Code'), ('texte', 'Texte libre')], default='qcm', max_length=50),
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('is_correct', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='users.apprenant')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='exercises.exercice')),
            ],
            options={
                'unique_together': {('exercice', 'apprenant')},
            },
        ),
    ]
