# Generated by Django 6.0.4 on 2026-04-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='courses.cours'),
        ),
        migrations.AddField(
            model_name='certification',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='certifications.inscription'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('apprenant', 'cours')},
        ),
    ]
