# Generated by Django 6.0.4 on 2026-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Certification'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription'},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='modules_termines',
        ),
        migrations.AddField(
            model_name='inscription',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
